settings:
  onlyplayerdamage: false
  progressbar:
    filler: "|"
    bars: 10
    incomplete_color: "c"
    complete_color: "a"

database:
  host: "172.18.0.1:3306"
  user: "user"
  pass: "pass"
  database: "database_name"

pickaxe:
  totalLevels: 500
  xp-base: 500
  lore:
    - "" # DO NOT TOUCH THIS LINE
    - "&5&lStatistics" # YOU MUST KEEP THE "Statistics" IN HERE!
    - "&d▎ &fLevel: &7%level% &8(&a%percentage%%&8)" # YOU MUST KEEP THE "level:" IN HERE
    - "&d▎ &fXP: &7%xp%/%xp_needed%" # YOU MUST KEEP THE "xp:" IN HERE
    - "&d▎ &fProgress: &8[%progressbar%&8]" # YOU MUST KEEP THE "Progress:" IN HERE
  rewards:
    1-400:
      - "[cmd] eco give %player% 100"
      - "[message] &bCongrats %player% you have reached level 1 on your pickaxe"