name: LevelTools
version: 1.0
main: me.mynqme.LevelTools.LevelTools
depend: [ PlaceholderAPI, NBTAPI, Multipliers]
author: MyNqme
commands:
  leveltools:
    description: LevelTools command for the leveltools plugin!
    aliases:
      - pickaxelevel
      - lvltools