name: LevelTools
version: 2.0.4
main: dev.tom974.LevelTools.Main
depend: [ PlasmaPrisonCore, PlaceholderAPI]
author: MyNqme
commands:
  leveltools:
    description: main command for the leveltools plugin!
    aliases:
      - pickaxelevel
      - lvltools