name: LevelTools
version: 2.0.4
main: me.mynqme.LevelTools.Main
depend: [ PlaceholderAPI, NBTAPI, Multipliers]
author: MyNqme
commands:
  leveltools:
    description: main command for the leveltools plugin!
    aliases:
      - pickaxelevel
      - lvltools